### ISSUE TITLE
CRITICAL() - report associated SPRING number

### ISSUE THREAD

**Issue by bencannell** [tkoziara/parmec#10]
Hi @tkoziara,

I’m looking into the calculation of CRITICAL() in a bit more detail. Would it be possible/simple for CRITICAL() to also output the spring number which is associated with the CRITICAL() value?

Presumably this could be multiple spring numbers (i.e. representing a certain interaction in one of our array type models), in which case perhaps CRITICAL() could report just one of these spring numbers? Or return a python list?

e.g.:

_(h, nums) = CRITICAL ()_

_h - critical time step_
_nums - list of SPRING numbers for which h is the CRITICAL() timestep_

Best regards,

Ben

**Comment by tkoziara** [comment]
Hi:)  b7de2d0 added the following functionality:
http://parmes.org/parmec/input_commands.html#critical
I will still look into extending this by a *perparticle* parameter which will provide a more accurate estimate. Note that, when many springs are attached to individual particles, the actual highest frequency estimate is determined by the collective action of all springs attached to a particle.

**Comment by tkoziara** [comment]
FYI, with 5ab402d we now have both options (per-spring and per-particle critical time steps) implemented; you can see an example application [here](https://github.com/tkoziara/parmec/blob/master/tests/spring_chain_critical.py); docs [as before](http://parmes.org/parmec/input_commands.html#critical); closing issue now; please test and reopen if needed:) T.
