### ISSUE TITLE
Potential bug in parmec changeset b723702

### ISSUE THREAD

**Issue by bencannell** [tkoziara/parmec#11]
Hi @tkoziara 

I think you may have introduced a bug in parmec changeset b723702 since the large multi-layer array models I have been able to simulate in changeset dd103c0 no longer produce results (nan values in output database).

Let me know if you need an example model. I haven't tested this with smaller models to see if it's a consistent issue across all the parmec models we've developed. Please let me know if you think there is a useful test case for me to run.

Many thanks,

Ben

(mention @stevebrasier)

**Comment by tkoziara** [comment]
Yes; thank you for reporting: I have looked into the change set and spotted a little bug; this also fixed a broken test for me so perhaps this is it; I am working on #10 now and I will commit all changes by the end of the day:)

**Comment by tkoziara** [comment]
Please try current commit:)

**Comment by bencannell** [comment]
Hi @tkoziara,

This can now be closed thank you :)
