### ISSUE TITLE
Potential bug in HISTORY command with "point="

### ISSUE THREAD

**Issue by bencannell** [tkoziara/parmec#12]
Hi @tkoziara,

I am getting an error when requesting output from parmec using the following HISTORY command:

`result1 = HISTORY(entity='DX',source=1,point=(1.1875, 1.425, 1.95975),h5file='test0rb.h5',h5last=True)`

The error is as follows:

`output.cpp: 2923 => HDF5 file read error: ANGVEL dataset missing`

Opening the .h5 files in paraview gives me access to ANGVEL results so perhaps there's an issue with accessing the .h5 files using the HISTORY command?

Note that I don't get this error if I remove the "point=" request in the HISTORY command.

I'm using parmec changeset dd103c0.

Many thanks,

Ben

(mention @stevebrasier)

**Comment by tkoziara** [comment]
OK, thanks for reporting:) Try >= dca0c42. Closing (do reopen if fails).
Tomek

**Comment by bencannell** [comment]
Thanks @tkoziara. I'll later today/tomorrow morning :)
Ben

**Comment by bencannell** [comment]
Hi @tkoziara, this fix works :)
Thanks,
Ben
