### ISSUE TITLE
Reduced Output for Solfec Viewer

### ISSUE THREAD

**Issue by bencannell** [tkoziara/parmec#15]
Hi @tkoziara,

Is there any provision for outputting a reduced Solfec format database which is compatible with the Solfec viewer?

i.e. a function similar to the XDMF_EXPORT function which allows the user to output results of a subset of modelled Dolfec bodies but exporting database files which are accessible by the Solfec viewer.

We find the solfec viewer much more user friendly for visualizing results than paraview.

Many thanks,

Ben

**Comment by tkoziara** [comment]
Ben, this is OK, I cam implement such functionality. But this is a Parmec issue tracker:)

**Comment by bencannell** [comment]
Ah! Thank you! I'll close and reopen in Solfec!
