### ISSUE TITLE
MODSPRING

### ISSUE THREAD

**Issue by bencannell** [tkoziara/parmec#2]
Hi @tkoziara. As discussed a while ago, see attached a proposal for a function "MODSPRING" which would allow us to implement something like solfec "RT_SPLIT" in parmec. Explanatory email to follow too.

[MODSPRING.txt](https://github.com/tkoziara/parmec/files/1245461/MODSPRING.txt)

@stevebrasier for info.

**Comment by tkoziara** [comment]
Documentation:
--------------
**MODSPRING** (tsprings, msprings, limits | curve, abs, nsteps, nfreq)

Modifies the spring curves of a user defined selection of springs (**msprings**) based on the spring
forces experienced by a different user defined selection of springs (**tsprings**). Modifications to
the spring curves occur during a simulation.

**tsprings**: tuple of unique spring numbers whose spring forces are assessed against a criteria defined by *limits*

**msprings**: tuple of unique spring numbers which are to be modified if *tsprings* meet the *limits* criteria (springs defined in *tsprings* are not modified unless also specificed in *msprings*)

**limits**: tuple of (min, max) force limit values, if either value is *None* then no failure limit is assumed e.g. (*None*, max) only has an upper failure limit; also min < max

**curve**: Python dictionary with: *key* (int): unique spring number (must be present in **msprings**), *value* (int),  time series number (TSERIES) defining the unload spring curve (default: a *zero curve* such that any displacement generates a spring force SF=0)

**abs**: boolean, if *True* then spring forces are converted to absolute values before summation of the spring forces (default: *False*)

**nsteps**: int, number of time steps between calls of MODSPRING() (default: 1)

**nfreq**: int, number of *nsteps* which *tsprings* exceed limits before the spring curves of *msprings* are modified (default: 1)

Assumptions:
----------------
1. "Failure" of *msprings* is based on the sum of the spring force values across all spring numbers
   defined in *tsprings*. This is a sum of absolute values if *abs=True*. Forces in all *tsprings* must 
   exceed the specific min/max values defined in *limits* for the spring curves to be modified
   (i.e. spring curve modification is an "and" operation, not "or").

   For example, if: 
	tsprings = (1,2)
	msprings = (3,4)
	limits = (-1.0, 1.0)

   then calling MODSPRING(tsprings, msprings, limits) would result in the spring force 'SF' being 
   assessed against their defined (-1.0, 1.0) limits. For the spring curves of springs 3 and 4 to be
   modified, the combined sum of the forces of springs 1 and 2 must be outside of the defined 
   limits for nfreq number of nsteps.

2. It is not valid for len(tsprings) = 0 or len(msprings) = 0

**Comment by bencannell** [comment]
I've just realised that I got the description of tsprings and msprings the wrong way around in the docstring. The docstring should read:

Modifies the spring curves of a user defined selection of springs (**_msprings_**) based on the spring
forces experienced by a different user defined selection of springs (**_tsprings_**). Modifications to
the spring curves occur during a simulation.

**Comment by bencannell** [comment]
@tkoziara, here is a suggestion for a more generalised version of MODSPRING. I'm not sure about which SPRING parameters it makes sense to be writeable during a simulation. Perhaps you have a better/more generalised solution?

[MODSPRING_v2.txt](https://github.com/tkoziara/parmec/files/1251325/MODSPRING_v2.txt)

**Comment by tkoziara** [comment]
Documentation:
------------------

**MODSPRING** (tsprings, msprings, limits, mods | abs, nsteps, nfreq)

Modifies writeable SPRING parameters of a user defined selection of springs (msprings) based on
the behaviour of a different user defined selection of springs (tsprings). Modifications to
the spring parameters occur during a simulation.


**tsprings**:  tuple of unique spring nums which are assessed against a "failure" criteria defined by
	   "limits"

**msprings**: tuple of unique spring nums which are to be modified if tsprings meet the "limits"
          criteria (spring nums defined in tsprings are not removed unless also specified in
          msprings)

**limits**:	  list of objects [object1, object2, ..., objectN] indicating entity specific validity
	  limits are:

		tuple (entity, mode, min, max), where entity/mode are defined in OUTPUT command
		and min/max values define the limits of validity (i.e. limits which must be exceeded in
		order for modifications to be applied). If either min/max value is None or blank then
		no modification limit is assumed e.g. (None, max) only has an upper modification limit,
		also min < max 

		TSERIES where points is a list of times and v is either 0 or 1 where 1 indicates
		a modification to SPRING parameters (once a parameter has been modified it cannot be
		reverted back to its original value by specifying a 0 TSERIES value, instead a
		separate call of MODSPRING must be used)

**mods**:     list of objects [object1, object2, ..., objectN] indicating SPRING parameter specific
	  modifications, valid objects are:
	
	  	tuple (spring_num, parameter, value), where spring_num is the unique int
		identifying the spring, parameter is a writeable SPRING parameter, and value
		is the value to be written to parameter (see SPRING for the parameter specific
		formats of value)

**abs**:	  boolean, if True then entities are converted to absolute values before assessment of 
          modification (default: False)

**nsteps**:	  int, number of timesteps between calls of MODSPRING() (default: 1)

**nfreq**:	  int, number of nsteps which tsprings exceed {limits} before the parameters of msprings
	  are modified (default: 1)


Assumptions:
----------------
1. Modification of msprings is based on the sum of the entity values across all spring nums defined in
   tsprings. This is a sum of absolute values if abs=True. Each entity is summed independently, 
   however all entities must exceed the specific min/max values defined in {limits} for failure
   to occur (i.e. failure is an "and" operation, not "or").

For example, if: 

	tsprings = (1,2)
	msprings = (3,4)
	limits = [('SF', 'SD', -1.0, 1.0), ('DISPL', 'SD', -0.5, 0.5)]
	mods =  [(3, 'point1', (0, 0, 0)), (4, 'spring', tms1)]

Then calling MODSPRING(tsprings, msprints, limits, mod) would result in the spring force 'SF' and spring stroke 'DISPL' being assessed against their defined min, max limits. For modification of springs 3 and 4 to be implemented, the forces and displacements in both springs 1 and 2 must be outside of the defined min, max limits. If these limits are exceeded then "point1" is adjusted on spring 3 and the spring curve of spring 4 is changed to TSERIES object tms1.

2. It is not valid for len(tsprings) = 0 or len(msprings) = 0

3. Attempts to write to a read-only SPRING parameter result in an ERROR

**Comment by tkoziara** [comment]
@bencannell I edited the specification of the simpler version of MODSPRING above; you can have a look and check whether it reflects your intention;

there is a nuance of how a general unloading curve is to be applied to each spring in *msprings*: should that be for each individual spring with a shift relative to its current displacement? in that case there it would be good to include an additional information about that into the specification/documentation;

**Comment by tkoziara** [comment]
@bencannell @stevebrasier 
I started prototyping this (generalising a bit); I am not clear about how the unloading curve would be applied; the default is to make the total force zero instantaneously - yes?

I am guessing that an unloading curve would be applied to every spring individually and would gradually bring their forces to zero - producing a negative force increment for both negative and positive displacement increments; So that would be a new type of "unloading curve" not related to the unloading curve defined within the SPRING command already;

Now, in a more general sense - does this command make sense at all when we allow the users to redefine the entire set of the SPRING command parameters? Can you see applications for that?

I generalised slightly the initial proposition by adding "entity" (default: SF) and "operator" (default: SUM) parameters;  I am wondering whether further modifications make sense; If not - perhaps instead of MODSPRING we could use UNSPRING?

Comments?:)

**Comment by tkoziara** [comment]
@bencannell @stevebrasier  FYI: I am going with the below for the time being; feel free to provide comments.

------

**UNSPRING** (tsprings, msprings, limits | entity, operator, abs, nsteps, nfreq, unload)

Undoes user defined selection of springs (msprings) based on the value of spring entities experienced by a different user defined selection of springs (tsprings). Modifications to the spring curves occur during a simulation. Undone springs remain in the simulation but generate zero forces.

• tsprings - tuple of unique spring numbers whose spring entities are assessed against a criteria defined by limits; must be nonempty

• msprings - tuple of unique spring numbers which are to be modified if tsprings meet the limits criteria (springs defined in tsprings are not modified unless also specified in msprings); must be nonempty

• limits - tuple of (min, max) tsprings operator entity limit values which need to be exceeded for msprings to be modified; if either value is None then no failure limit is assumed e.g. (None, max) only has an upper failure limit; also min < max

• entity - scalar spring entity string: (spring stroke) 'STROKE', (spring total force) 'STF', (spring force without damping) 'SF', cf. [subsec:HISTORY] and [subsec:OUTPUT]; default: 'SF'

• operator - collective tsprings operator string: 'SUM', 'MIN', 'MAX'; default: 'SUM'

• abs - boolean, if True then spring forces are converted to absolute values before summation of the spring forces; default: False

• nsteps - int, number of time steps between calls of UNSPRING; default: 1

• nfreq - int, number of nsteps for which tsprings exceed limits before msprings are modified; default: 1

• unload - Python dictionary (i.e. unload[key] = value), where key (int) - unique spring number (must be present in msprings) and value (int) - time series number (TSERIES) defining the unload spring curve; an unloading curve must originate at zero and increase monotonically; once modification is activated, for each spring in msprings, the unloading curve is individually applied with a shift specific to the current displacement; both negative and positive displacement increments decrease total spring forces until zero; the spring force remains zero ever after; dashpot force is zero during unloading; default: instantaneous unloading to zero total force

By default, modification of msprings is based on the sum of the elastic spring force values across all spring numbers defined in tsprings. This is a sum of absolute values if abs = True. Forces in all tsprings must exceed the specific min/max values defined in limits for the spring curves to be modified (i.e. spring curve modification is an and operation, not or). For example:

tsprings = (1,2)

msprings = (3,4)

limits = (-1.0, 1.0)

UNSPRING(tsprings, msprings, limits)

results in the resultant elastic spring force (SF) being assessed against the (-1.0, 1.0) limits. For the spring curves of springs 3 and 4 to be modified, the sum of the forces of springs 1 and 2 must be outside of the (-1.0,1.0) limits for nfreq (=1) number of nsteps (=1).

**Comment by tkoziara** [comment]
@bencannell @stevebrasier 
Hey, now I am thinking that this should be combined with the CPLANE (contact plane) command; When unloading is concluded, optionally a contact plane could be activated; Yes? This is what you would like for a complete functionality I am guessing;

num = CPLANE (master, plane, slave, points, spring, dashpot | active)

so that we can create inactive planes by default; then

UNSPRING ( ... | ... , cplane)

where a given contact plane gets activated after unloading.

**Comment by bencannell** [comment]
Hi @tkoziara 

Firstly, I agree that the UNSPRING definition covers our current "known" applications for implementing runtime "failure" in parmec. If you're happy to develop this more specific function (compared to MODSPRING) then we're happy to got with UNSPRING :)

Secondly, you are correct that we need a CPLANE capability due to the loss of constraint following removal of springs, however I don't think it needs to be over-complicated by activating this feature following failure of a key. Rather, we were planning on changing the model at t=0s to include CPLANE definitions rather than the current direct contact spring definition. Although, do you think there would be a significant enough computational cost associated with the CPLANE functionality to support implementing CPLANE during the analysis?

**Comment by bencannell** [comment]
Further to the above, in my email at 15:08 on 23/08/2017, I mentioned that we also require a method to modify a spring curve during a simulation, based on the elapsed analysis time. For example, initially a spring may have the following curve:

![image](https://user-images.githubusercontent.com/29304199/30203754-0e8d7b4a-947b-11e7-94e1-87e01a2615f0.png)

Which would then be changed to the following at t=1s:

![image](https://user-images.githubusercontent.com/29304199/30203832-563b37d4-947b-11e7-8ef4-9b3cd280200e.png)

Seeing as UNSPRING() seems to be the cleanest approach for implementing runtime failure, then perhaps MODSPRING could be simplified to:

MODSPRING(msprings, time, curve)

where the spring curve of _msprings_ is modified at _time_ to be _curve_.

What do you think?

**Comment by tkoziara** [comment]
Regarding CPLANE:
There would not be a significant cost of having some contact planes inactive to begin with and later activated. With the idea of having such planes active from the start there would be (?) an issue with such contacts generating forces in addition to the forces generated by springs?

Regarding UNSPRING:
I am in the process of implementing it as specified:)

Regarding MODSPRING:
Would a more general interface be appropriate at all:
MODSPRING (msprings, time | spring, dashpot, direction, planar, unload, ylim)?

**Comment by bencannell** [comment]
Hi

Regarding CPLANE:
I envisaged that CPLANE would be used to model direct contact i.e. normal contact between particles, in place of the current direct contact springs we use (so there wouldn't be any duplication of contact force here). However, I see you point when considering the shear springs (which are defined in a global orientation). In theory, when the bricks experience large global rotations, the orientation of the CPLANE springs will tend towards the same orientation as the shear springs. However, rotations this large are likely to occur when shear springs have failed or other areas of the model are becoming invalid. So, in summary, we should keep this as a limitation for the time being, and include the CPLANE contacts from t=0s. Maybe @stevebrasier has a different idea?

Regarding MODSPRING:
Yes, your suggestion would be approriate :)

**Comment by tkoziara** [comment]
In addition to CPLANE, here is a more general idea:
CPOLY (part, poly, color | active)
where contact between such convex, oriented polygons could be detected. This could be used in combination with GRANULAR. Combined with UNSPRING activation this would extend into modelling general rigid-body-spring systems (failing gradually) or it could be used from the start to handle contact between general geometries:)
We are entering the area of basic design: contacts are colour coded and detected - while springs are prescribed. So perhaps CPLANE could rather be SPLANE (a spring plane) where springs would span between moving-and-rotating points projected onto moving-and-rotating plane (in the direction normal to the plane).

**Comment by bencannell** [comment]
hi @tkoziara 

Do you need additional input from myself or @stevebrasier to progress this?

**Comment by tkoziara** [comment]
I think I can implement SPLANE in a usable state to start with;

**Comment by tkoziara** [comment]
@bencannell @stevebrasier I marked UNSPRING as experimental and I am closing this issue now; You can have a look at the [manual page](http://parmes.org/parmec/input_commands.html#unspring) and the [test examples](https://github.com/tkoziara/parmec/tree/master/tests) (starting from *unspring*) and let know in case you run into anything;
