### ISSUE TITLE
HISTORY

### ISSUE THREAD

**Issue by bencannell** [tkoziara/parmec#3]
Hi @tkoziara 

Following our discussion last week, would it be possible to modify or make an addition to the HISTORY command, such that results can be accessed after an analysis has been completed. This would serve as an alternative to using paraview, the main benefit being that the user can make use of the _"point"_ argument already implemented in the HISTORY command without having to perform transformations manually outside of parmec. The interface currently provided for HISTORY is sufficient.

**Comment by tkoziara** [comment]
Hi @bencannell, @stevebrasier 
This is now implemented via optional HISTORY parameters **h5file** and **h5last**. See [docs](http://parmes.org/parmec/input_commands.html#history) and [example](https://github.com/tkoziara/parmec/blob/master/tests/history_h5file.py).

**Comment by bencannell** [comment]
Thank you @tkoziara
