### ISSUE TITLE
SPLANE command

### ISSUE THREAD

**Issue by tkoziara** [tkoziara/parmec#4]
Implement springs plane as discussed in #2

**Comment by tkoziara** [comment]
I think I will go with the below to begin with
`num = SPLANE (master, plane, slave, points, spring, dashpot | active)`
so that one can create inactive planes if needed; and then use
`UNSPRING ( ... | ... , splane)`
to activate a spring plane upon unloading. CC: @stevebrasier, @bencannell

**Comment by bencannell** [comment]
Hi @tkoziara, yes, your suggestion makes sense. Please could you send through the docstring for SPLANE to ensure I'm not misunderstanding your proposal?

**Comment by tkoziara** [comment]
In fact, I am wondering, whether we really need SPLANE; Why not just slightly modify the SPRING command instead? E.g.

```
sprnum = SPRING (part1, geom1, part2, point2, spring |
                 dashpot, direction, planar, unload, ylim, active)
```

where former *point1* was replaced by *geom1* which now is:

**geom1** - tuple (x,y,z) defining a point moving with the first particle; or a list [(px, py, pz), (nx, ny, nz)] defining a referential [*point*, *normal*] plane moving with the first particle; when a plane is given the spring direction and stroke are calculated from a projection of **point2** onto this plane -- in this case the input arguments **direction** and **planar** are ignored;
**active** - active spring Boolean flag (default: *True*); inactive springs can be activated as a result of an UNSPRING action;

And then we can have:

```
UNSPRING ( ... | ... , activate)
```
where:

**activate** - is a list [s1, s2, ..., sN] of inactive springs - to be activated upon unloading;

The point is that we already have developed and optimised spring functionality and a spring plane simply creates a number of springs; Extending the current spring functionality could be more efficient; But also, an SPLANE command could be added as a wrapper around such extended SPRING functionality; So there would be need for another internal representation of the spring plane;

What's your view?

**Comment by tkoziara** [comment]
Ben, I started by generalising the [SPRING](http://parmes.org/parmec/input_commands.html#spring) command; This includes the requested functionality; I will look into the (de)activation idea and report when I have tested this successfully; I think we may simply do away with SPLANE;

**Comment by tkoziara** [comment]
@bencannell @stevebrasier I modified the [SPRING](http://parmes.org/parmec/input_commands.html#spring) command by turning **point2** into **geom2** and allowing to pass a plane definition; This implements the requested functionality; A delayed activation of springs is also included when **inactive** flag is used -- in combination with [UNSPRING](http://parmes.org/parmec/input_commands.html#unspring) **activate** argument; Have a look at the *spring* and *unspring* [test examples](https://github.com/tkoziara/parmec/tree/master/tests) and do report any issues that you encouter; I am closing this issue now;

**Comment by bencannell** [comment]
Hi @tkoziara 

Could you provide an example of the **geom2** functionality where a referential plane is defined as moving with the second particle. I think you have only provided an example where the plane is spatially fixed, where we require the former? 

I've set up a small test case but it doesn't produce expected behaviour so it would be useful to see an example of how you intended for it to be used.

Many thanks,

Ben

**Comment by tkoziara** [comment]
Hi Ben,
Please check out the latest commit. I made a little fix and added a new test [example](https://github.com/tkoziara/parmec/blob/master/tests/spring_contact_moving_plane.py) and [video](https://www.youtube.com/watch?v=ez3ZrU_7KIY).
Best,
Tomek

**Comment by tkoziara** [comment]
@bencannell hey:) do let me know whether I can now close this issue;

**Comment by bencannell** [comment]
Hi @tkoziara, yes happy for this to be closed
