### ISSUE TITLE
UNSPRING output

### ISSUE THREAD

**Issue by bencannell** [tkoziara/parmec#5]
Hi @tkoziara,

It would be beneficial to us to be able to determine the time during an analysis at which a spring was deactivated by UNSPRING. 

One method could be for us to track spring forces and record the time at which they reach the limit. I think we should be able to do this using the existing parmec interface.

I think a better method would be an additional OUTPUT entity called "ACTIVE" (perhaps?) which returns TRUE or FALSE depending on whether a spring is active or inactive at a given time point. Would it be possible to include this functionality in parmec? Or is there an equivalent already available? Or do you have a better suggestion?

Thanks!

Ben

**Comment by tkoziara** [comment]
Hi,

Yes - this can be simply included; Perhaps even - instead of outputting
time histories of states "yes, yes, yes, ..., yes, no, no, no, ..." - it
could be more elegant to output individual deactivation events - e.g. as a
simple table of spring numbers and times; Could be a part of output and
reported in a way that can be vied in Paraview in a table format; Could
also perhaps be included into HISTORY;

Best regards,
Tomek

**Comment by bencannell** [comment]
Brilliant, thanks.

Yes individual deactivation events would be fine. I think the main outputs we would like to be able to produce are:
- Tables (lists) of times when springs were deactivated.
- Ability to visualise deactivations in Paraview.

So I think what you're proposing (Paraview and HISTORY) would be perfect.

Best regards,

Ben

**Comment by bencannell** [comment]
I would also be useful to record when a spring was activated in a similar fashion.

**Comment by bencannell** [comment]
Hi @tkoziara,

Happy new year!

Have you managed to make any progress on this? Do we need to provide any additional input?

Best regards,

Ben

**Comment by tkoziara** [comment]
Hi,

Happy, happy:)

No, I am working on feedback to Philippe's report now. This one is coming
next.

In the meantime, feel free to paste in any specification you'd like to
guide my implementation. It's OK if not - I will implement something that
will work and you will be able to provide feedback and refine it this way.

Best regards,
Tomek

**Comment by tkoziara** [comment]
:) See this blog post: http://parmes.org/blog/unspring_and_spring_state.html

**Comment by tkoziara** [comment]
@bencannell hey:) do let me know whether I can now close this issue;

**Comment by bencannell** [comment]
Hi @tkoziara, yes happy for this to be closed
