### ISSUE TITLE
Spring Stroke Offset

### ISSUE THREAD

**Issue by bencannell** [tkoziara/parmec#8]
Hi @tkoziara,

Would it be possible to include some additional functionality in the spring curve command to modify spring curves with time?

For example, we would like to be able to adjust the red dashed spring curve in the image below to become the blue solid spring curve over time.

![stroke_offset](https://user-images.githubusercontent.com/29304199/37833664-ca04f1c4-2ea3-11e8-9303-57ac36578321.png)

The change to the API could be the following:

sprnum = SPRING (part1, point1, part2, geom2, spring | dashpot, direction, planar, unload, ylim, inactive, strokeoffset)

Where "strokeoffset" is an adjustment applied to all stroke values of the spring curve (dashpot unchanged), defined as a list or TSERIES number: [time1,strokeoffset1,time2,strokeoffset2,...,timen,strokeoffsetn]. The time values must be monotonically increasing. Ideally no limitation is imposed on strokeoffset values (however we currently intend on using either monotonically increasing or monotonically decreasing values).

Or perhaps you could suggest a better alternative?

The reason for this request is that we are intending on running a model of an array where components positioned "on-pitch" at t=0s would experience an initial overclosure with adjacent components, i.e. spring forces would be non-zero at t=0s. To avoid having initial strain energy in the model, we would like to position components on pitch with spring curves defined such that spring forces are 0 at t=0s, then gradually adjust these spring curves over time until the target initial configuration is achieved.

Best regards,

Ben

(mention @stevebrasier)

**Comment by tkoziara** [comment]
Hi @bencannell , @stevebrasier ; Yes, this should be OK to implement; I will look into this this and in the coming week:) Very nice picture by the way! :) (if you don't mind I will use it in the documentation of the updated SPRING command);

**Comment by tkoziara** [comment]
Have a look: http://parmes.org/parmec/input_commands.html#spring
This is on GitHub now, but has not been tested yet:) T.

**Comment by tkoziara** [comment]
FYI, initially made work; Try on [this example](https://github.com/tkoziara/parmec/blob/master/tests/spring_stroke_offset.py):) closing the issue; T.

**Comment by bencannell** [comment]
Hi @tkoziara, I've tested this implementation and it produces expected results.

**Comment by bencannell** [comment]
Thank you!

**Comment by tkoziara** [comment]
Good :)
