### ISSUE TITLE
Issue with SLA / DCB models

### ISSUE THREAD

**Issue by PMartinuzzi** [tkoziara/parmec#9]
Current version of lsdyna2parmec python script does not convert DCB correctly, leading to completely wrong results (model exploding)

The issue is suspected to be due to incorrect Inertia matrix for some DCB bricks (defined with a local coordinate system).

Attached file:
- The LS_DYNA keyfile (extention .key modified into .txt to be able to upload)
[ST_1L_quarter_50percent.txt](https://github.com/tkoziara/parmec/files/1931608/ST_1L_quarter_50percent.txt)
- The parmec python file after using keyfile2parmec.py (extention .key modified into .txt to be able to upload)
[ST_1L_quarter_50percent_converted.txt](https://github.com/tkoziara/parmec/files/1931609/ST_1L_quarter_50percent_converted.txt)

Example of error in inertia:
num = ANALYTICAL (inertia = [0.000299975, 0.000299975, 0.0003975, -0.000131515, 0, -0.000131515], mass = 0.308, position = (1.92096, 0.377214, 0.15885))
RESTRAIN (num, [0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0, 0.0])
pid2num[3073301] = num

**Comment by bencannell** [comment]
Hi @PMartinuzzi,

Just to clarify, does the input deck "ST_1L_quarter_50percent_converted.txt" explode when you run it using the parmec4 executable? If not, could you send the input deck which does explode, exactly as you are running it?

The above parmec input deck doesn't do anything if I run it. Perhaps since the input motion curve (103) doesn't apply any motion.

Best regards,

Ben

**Comment by bencannell** [comment]
Hi @PMartinuzzi,

I had a quick look at the DYNA model you have provided and struggled to trace it back to a model in our registers. As such, there is perhaps a chance that the DYNA model itself isn't correct.

Have you managed to run the model using DYNA?

I've tested this model ([ST_1L_tester.txt](https://github.com/tkoziara/parmec/files/1943363/ST_1L_tester.txt)) using the keyfile2parmec.py converter provided and it seems to run ok. This model also includes DCBs. I can't comment on whether the behaviour is reasonable, however it doesn't "explode" as you observe in your model.

Best regards,

Ben

**Comment by PMartinuzzi** [comment]
Hi,
If you run this file nothing will move because tms103 is always 0 and gravity is in the z direction which is blocked for every component.

If you apply a gravity in the x direction (GRAVITY (tms100, 0.0, 0.0)) then the problem should explode.

Please let me know how it goes (sorry I intended to send you that file but I made a mistake when sending the file).

I cannot run models with LS_DYNA, but the keyfile comes from the same generator as the one  I used for intact models.

Regards,
Philippe.

**Comment by tkoziara** [comment]
Just starting to look at this and a quick observation is that the z-direction for gravity seems to be a natural one, given the picture:
<img width="591" alt="issue9tk1" src="https://user-images.githubusercontent.com/2198068/40647619-99cf933e-632c-11e8-8e8a-fa4a6ceaaaa8.png">
I will carry on pasting in some comments as I keep looking - this may help us enliven this issue a little bit:)

**Comment by tkoziara** [comment]
Indeed, I run a 4s simulation with GRAVITY (tms100, 0.0, 0.0) and here is the result:
![issue9tk1](https://user-images.githubusercontent.com/2198068/40648879-c69ee9c0-632f-11e8-8847-320317618b6d.gif)
I don't know how this model is set up - perhaps it is not supposed to work with gravity going sideways:) But let me try with a smaller step size and see. I am thinking, that gravity would typically be along z, but there would be a sideways excitation - but in this input I don't see a time history that looks like an excitation in the input file; of course, I am making the simulation much shorter for those tests.

**Comment by tkoziara** [comment]
I run a 5 second simulation with time step 1E-5 (5x smaller then the original). It did not blow up but stabilised, several initial frames are included below. Let us remember that this is explicit nonlinear modelling, :), and depending on circumstances we may need adjust the time step to obtain stable runs. I hope that this is helpful enough:) Please, Philippe, Ben, if you have any comments, include them below.
![issue9tk2](https://user-images.githubusercontent.com/2198068/40651860-0b01bc44-6337-11e8-9f65-c22c1a7956ef.gif)

**Comment by PMartinuzzi** [comment]
Hi both,

Thanks for progressing on this;

A few comments:
- Gravity in the z direction is indeed the 'normal' loading. Since all bricks are blocked in the Z direction, it would have no effect on the current model. In this case we apply it in the x direction to have some loading to test, even if it is not physical.
- I know that explicit resolution requires small time steps, otherwise there is numerical creation of energy that could explain the fact that the model explodes after a few time steps. Thanks for suggesting to reduce the time steps, I thought I tried with no effect on the results.
- However I doubt that the problem is solved: the reason why I say that is that if you use intact models, there is no way the model would behave like this even with a larger time step. This 'model exploding' only appears when introducing DCBs, and only some directions of DCB. My impression is that the inertia matrice derived from the LS-DYNA keyfile is not interpreted correctly, which results in negative/strongly unphysical values, which causes the problem. I did try to use DCB models with same inertia matrices for all fuels bricks and the model was behaving properly (although slightly different from what it should do due to differences in mass and inertia).

Is it physically possible to have negative values in inertia matrices as shown below:
ANALYTICAL (inertia = [0.000299975, 0.000299975, 0.0003975, -0.000131515, 0, -0.000131515]?
For me it is not and this is the source of the problem.

- Unfortunately I will not be able to run any Parmec models for until mid-June as I am working out of office and do not have access to my regular computers.

Regards,
Philippe.

**Comment by tkoziara** [comment]
OK, I will continue having a look then. Regarding inertia properties ([as documented](http://parmes.org/parmec/input_commands.html#analytical)), the first three values are the diagonal, Ixx, Iyy, Izz, and they are positive. The remaining three values are the off diagonal entries, Ixy, Ixz, Iyz, and it is ok for them to be negative. [This page](http://farside.ph.utexas.edu/teaching/336k/Newtonhtml/node64.html) helped me refresh my own memory about how inertia tensor is calculated: and indeed the off-diagonals can be negative. I think only the entire matrix needs to be positive definite (so that any angular velocity will produce positive kinetic energy). But indeed, there may still be a bug of some sort with how these values are calculated based on LS-DYNA's convention. I will have another look and check through this. Thank you for persisting on this. Tomek

**Comment by tkoziara** [comment]
Based on Philippe's email and the submitted [bug fix](https://github.com/tkoziara/parmec/commit/55947274f6979dd9ecc6474b35eed26af6d0dde2), I am closing this issue.
